Fix FN_PUBLIC_LB_URL when TLS is enabled
fnproject/fn-helm pull request #52
Opened 2019-03-17 04:32 UTC by devcamcar

2019-03-17 04:41 UTC, denismakogon requested changes
Thanks, you can make it slightly simpler without duplicating the whole URL definition just for the one character.
Take a look at FN_DB_URL (create environment var that will contain the whole line without protocol prefix, then use it as a reference  `https://($FN_PUBLIC_LB_ENDPOINT)` )

2019-03-18 10:37 UTC, denismakogon commented on fn/templates/fn-deployment.yaml
> +            value: https://{{ .Release.Name }}.{{ .Values.fn_lb_runner.service.ingress_hostname }}:{{ .Values.fn_lb_runner.service.port }}
```yaml
- name: FN_PUBLIC_LB_SCHEMA
{{- if .Values.tls.enabled }}
  value: https
{{ else }}
  value: http
{{- end }}
- name: FN_PUBLIC_LB_URL:
  value: $(FN_PUBLIC_LB_SCHEMA)://{{ .Release.Name }}.{{ .Values.fn_lb_runner.service.ingress_hostname }}:{{ .Values.fn_lb_runner.service.port }}
```

2019-03-19 21:47 UTC, devcamcar commented on fn/templates/fn-deployment.yaml
> +            value: https://{{ .Release.Name }}.{{ .Values.fn_lb_runner.service.ingress_hostname }}:{{ .Values.fn_lb_runner.service.port }}
Done by using templates now

2019-03-20 05:10 UTC, denismakogon requested changes

2019-03-20 05:10 UTC, denismakogon commented on fn/templates/fn-deployment.yaml
> +            value: https://{{ template "fn.public_lb_url" . }}
that's too complicated and hard to search for references,
here's what you need to do:
```yaml
- name: FN_PUBLIC_LB_SCHEMA
{{- if .Values.tls.enabled }}
  value: https
{{ else }}
  value: http
{{- end }}
- name: FN_PUBLIC_LB_URL:
  value: $(FN_PUBLIC_LB_SCHEMA)://{{ .Release.Name }}.{{ .Values.fn_lb_runner.service.ingress_hostname }}:{{ .Values.fn_lb_runner.service.port }}
```
that's it, looks similar to what we have for FN_DB_URL (clear and simple)

FYI, templates are for more complex logic, but not for the one-line templates.

2019-03-20 09:44 UTC, denismakogon approved these changes

2019-03-20 09:44 UTC, denismakogon commented on fn/templates/fn-deployment.yaml
> +            value: https://{{ template "fn.public_lb_url" . }}
you know, actually, ignore my comment, these two fixes doing the same but in a different manner, which is totally fine.

2019-03-20 09:45 UTC, merged